[package]
name = "base"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
colored = { workspace = true }
flexi_logger = { workspace = true }
log = { workspace = true }
